- name: Upload Episode from YouTube To Anchor.Fm
  uses: Schrodinger-Hat/youtube-to-anchorfm@v0.1.5

on:
  push:
    paths: 
      - episode.json
    branches: [master]

jobs:
  upload_episode:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install And Configure youtube-dl
        run: |
          sudo curl -k -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
          sudo chmod a+rx /usr/local/bin/youtube-dl
      - name: Install Deps, donwload audio file from youtube video defined in episode.json and upload to anchor
        run: |
          npm install
          npm audit fix
          npm run upload
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}